---

- name: Capture show output
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:

    - name: Task 1 - Exec show command
      ios_command:
        commands:
        - show run | i username
        - show run | i ip route
      register: config

    - name: Task 2 - Creating a reports folder (if not already present)
      file:                                            ## file is the Ansible module we are invoking
        name: /etc/ansible/show-output                     ## the name to give the new directory
        state: directory                               ## parameter of the file module, creates a directory
      run_once: true                                   ## instructs Ansible to only run this task once for the batch of hosts targeted in the playbook

    - name: Task 3 - Save output to local directory
      copy:
#        content: "{{ config.stdout | replace('\\n', '\n') }}" # Выводится все команды в одну строчку нужно опфикись позже
        content: "{{ config.stdout }}"
        dest: /etc/ansible/show-output/{{ inventory_hostname }}.ios

    - name: Task 4 - Consolidating the device reports
      assemble:                                        ## assemble is the Ansible module we are invoking
        src: /etc/ansible/show-output                               ## parameter of the assemble module, path to the directory containing the individual device reports
        dest: /etc/ansible/show-output/show_output_report.ios            ## parameter of the assemble module, the file to create using the concatenation of the individual device reports
      delegate_to: localhost                           ## runs this task on our Ansible control node
      run_once: true