---

- name: Compare running and golden configuration files
  hosts: routers
  connection: network_cli
  gather_facts: no

  vars:
    - cfg_active_path: /etc/ansible/data/audit/{{ date.stdout }}_at_{{ time.stdout }}/{{ inventory_hostname }}_active.cfg
    - cfg_golden_path: /etc/ansible/data/goldencfg/router-1_gold.cfg
    - cfg_delta_path: /etc/ansible/data/audit/{{ date.stdout }}_at_{{ time.stdout }}/{{ inventory_hostname }}_delta.cfg

  tasks:

    - name: Task 1 - Accept ansible net hostname
      ios_facts:
        gather_subset: all

    - name: Task 2 - Get current date
      local_action: command date +%Y-%b-%d
      register: date

    - name: Task 3 - Get current time
      local_action: command date +%H:%M
      register: time

    - name: Task 4 - Creating a reports folder (if not already present)
      file:                                            ## file is the Ansible module we are invoking
        name: /etc/ansible/data/audit/{{ date.stdout }}_at_{{ time.stdout }}            ## the name to give the new directory
        state: directory                               ## parameter of the file module, creates a directory
      run_once: true                                   ## instructs Ansible to only run this task once for the batch of hosts targeted in the playbook

    - name: Task 5 - Get running-config
      ios_command:
        commands:
         - sh conf
      register: config

    - name: Task 6 - Save output to local directory
      copy:
        content: "{{ config.stdout[0] | replace('\\n', '\n') }}"
        dest: /etc/ansible/data/audit/{{ date.stdout }}_at_{{ time.stdout }}/{{ inventory_hostname }}_active.cfg

    - name: Task 7 - Find difference in configs and copy to file
      shell: |
        diff -u {{ cfg_active_path }} {{ cfg_golden_path }} > {{ cfg_delta_path }}
        diff -u {{ cfg_active_path }} {{ cfg_golden_path }}
      register: cfg_delta
      ignore_errors: true # разобраться на досуге почему выдает ошибку

    - name: Tasks 9 - Show difference
      debug:
        msg: "{{ cfg_delta.stdout_lines }}"

    - name: Tasks 10 - Done
      debug:
        msg: "All tasks has been done on {{ date.stdout }} at {{ time.stdout }}."
